import { TRPCError } from "@trpc/server";
import type { TrpcContext } from "./context";

export type PermissionKey =
  | "POS_CREATE" | "POS_READ" | "POS_UPDATE" | "POS_DELETE"
  | "BILLING_CREATE" | "BILLING_READ" | "BILLING_UPDATE" | "BILLING_DELETE"
  | "INVOICE_CREATE" | "INVOICE_READ" | "INVOICE_UPDATE" | "INVOICE_DELETE" | "INVOICE_APPROVE"
  | "ACCOUNTING_READ" | "ACCOUNTING_CREATE" | "ACCOUNTING_APPROVE"
  | "INVENTORY_READ" | "INVENTORY_CREATE" | "INVENTORY_UPDATE" | "INVENTORY_DELETE"
  | "CUSTOMER_READ" | "CUSTOMER_CREATE" | "CUSTOMER_UPDATE" | "CUSTOMER_DELETE"
  | "PRODUCT_READ" | "PRODUCT_CREATE" | "PRODUCT_UPDATE" | "PRODUCT_DELETE"
  | "PAYMENT_READ" | "PAYMENT_CREATE" | "PAYMENT_APPROVE"
  | "QUOTE_READ" | "QUOTE_CREATE" | "QUOTE_UPDATE" | "QUOTE_APPROVE"
  | "REPORTING_READ" | "REPORTING_FINANCIAL" | "REPORTING_INVENTORY"
  | "SECURITY_READ" | "SECURITY_MANAGE"
  | "USER_MANAGE" | "ROLE_MANAGE" | "SETTINGS_MANAGE"
  | "VOUCHER_CREATE" | "VOUCHER_READ" | "VOUCHER_APPROVE"
  | "PURCHASE_CREATE" | "PURCHASE_READ" | "PURCHASE_APPROVE"
  | "PHARMACY_READ" | "PHARMACY_CREATE" | "PHARMACY_APPROVE"
  | "WEBSTORE_READ" | "WEBSTORE_MANAGE"
  | "AI_READ" | "AI_ANALYZE"
  | "EXPORT_READ" | "IMPORT_CREATE";

export const PERMISSIONS: Record<PermissionKey, string> = {
  POS_CREATE: "POS_CREATE", POS_READ: "POS_READ", POS_UPDATE: "POS_UPDATE", POS_DELETE: "POS_DELETE",
  BILLING_CREATE: "BILLING_CREATE", BILLING_READ: "BILLING_READ", BILLING_UPDATE: "BILLING_UPDATE", BILLING_DELETE: "BILLING_DELETE",
  INVOICE_CREATE: "INVOICE_CREATE", INVOICE_READ: "INVOICE_READ", INVOICE_UPDATE: "INVOICE_UPDATE", INVOICE_DELETE: "INVOICE_DELETE", INVOICE_APPROVE: "INVOICE_APPROVE",
  ACCOUNTING_READ: "ACCOUNTING_READ", ACCOUNTING_CREATE: "ACCOUNTING_CREATE", ACCOUNTING_APPROVE: "ACCOUNTING_APPROVE",
  INVENTORY_READ: "INVENTORY_READ", INVENTORY_CREATE: "INVENTORY_CREATE", INVENTORY_UPDATE: "INVENTORY_UPDATE", INVENTORY_DELETE: "INVENTORY_DELETE",
  CUSTOMER_READ: "CUSTOMER_READ", CUSTOMER_CREATE: "CUSTOMER_CREATE", CUSTOMER_UPDATE: "CUSTOMER_UPDATE", CUSTOMER_DELETE: "CUSTOMER_DELETE",
  PRODUCT_READ: "PRODUCT_READ", PRODUCT_CREATE: "PRODUCT_CREATE", PRODUCT_UPDATE: "PRODUCT_UPDATE", PRODUCT_DELETE: "PRODUCT_DELETE",
  PAYMENT_READ: "PAYMENT_READ", PAYMENT_CREATE: "PAYMENT_CREATE", PAYMENT_APPROVE: "PAYMENT_APPROVE",
  QUOTE_READ: "QUOTE_READ", QUOTE_CREATE: "QUOTE_CREATE", QUOTE_UPDATE: "QUOTE_UPDATE", QUOTE_APPROVE: "QUOTE_APPROVE",
  REPORTING_READ: "REPORTING_READ", REPORTING_FINANCIAL: "REPORTING_FINANCIAL", REPORTING_INVENTORY: "REPORTING_INVENTORY",
  SECURITY_READ: "SECURITY_READ", SECURITY_MANAGE: "SECURITY_MANAGE",
  USER_MANAGE: "USER_MANAGE", ROLE_MANAGE: "ROLE_MANAGE", SETTINGS_MANAGE: "SETTINGS_MANAGE",
  VOUCHER_CREATE: "VOUCHER_CREATE", VOUCHER_READ: "VOUCHER_READ", VOUCHER_APPROVE: "VOUCHER_APPROVE",
  PURCHASE_CREATE: "PURCHASE_CREATE", PURCHASE_READ: "PURCHASE_READ", PURCHASE_APPROVE: "PURCHASE_APPROVE",
  PHARMACY_READ: "PHARMACY_READ", PHARMACY_CREATE: "PHARMACY_CREATE", PHARMACY_APPROVE: "PHARMACY_APPROVE",
  WEBSTORE_READ: "WEBSTORE_READ", WEBSTORE_MANAGE: "WEBSTORE_MANAGE",
  AI_READ: "AI_READ", AI_ANALYZE: "AI_ANALYZE",
  EXPORT_READ: "EXPORT_READ", IMPORT_CREATE: "IMPORT_CREATE",
};

export const ROLE_DEFINITIONS: Record<string, PermissionKey[]> = {
  owner: Object.values(PERMISSIONS),
  admin: ["POS_CREATE","POS_READ","POS_UPDATE","POS_DELETE","BILLING_CREATE","BILLING_READ","BILLING_UPDATE","BILLING_DELETE","INVOICE_CREATE","INVOICE_READ","INVOICE_UPDATE","INVOICE_DELETE","INVOICE_APPROVE","ACCOUNTING_READ","ACCOUNTING_CREATE","ACCOUNTING_APPROVE","INVENTORY_READ","INVENTORY_CREATE","INVENTORY_UPDATE","INVENTORY_DELETE","CUSTOMER_READ","CUSTOMER_CREATE","CUSTOMER_UPDATE","CUSTOMER_DELETE","PRODUCT_READ","PRODUCT_CREATE","PRODUCT_UPDATE","PRODUCT_DELETE","PAYMENT_READ","PAYMENT_CREATE","PAYMENT_APPROVE","QUOTE_READ","QUOTE_CREATE","QUOTE_UPDATE","QUOTE_APPROVE","REPORTING_READ","REPORTING_FINANCIAL","REPORTING_INVENTORY","SECURITY_READ","SECURITY_MANAGE","USER_MANAGE","ROLE_MANAGE","SETTINGS_MANAGE","VOUCHER_CREATE","VOUCHER_READ","VOUCHER_APPROVE","PURCHASE_CREATE","PURCHASE_READ","PURCHASE_APPROVE","PHARMACY_READ","PHARMACY_CREATE","PHARMACY_APPROVE","WEBSTORE_READ","WEBSTORE_MANAGE","AI_READ","AI_ANALYZE","EXPORT_READ","IMPORT_CREATE"],
  manager: ["POS_CREATE","POS_READ","POS_UPDATE","POS_DELETE","BILLING_CREATE","BILLING_READ","INVOICE_CREATE","INVOICE_READ","INVOICE_UPDATE","INVENTORY_READ","INVENTORY_CREATE","INVENTORY_UPDATE","CUSTOMER_READ","CUSTOMER_CREATE","CUSTOMER_UPDATE","PRODUCT_READ","PRODUCT_CREATE","PRODUCT_UPDATE","PAYMENT_CREATE","QUOTE_CREATE","QUOTE_UPDATE","REPORTING_READ","REPORTING_FINANCIAL","PHARMACY_READ"],
  accountant: ["ACCOUNTING_READ","ACCOUNTING_CREATE","ACCOUNTING_APPROVE","BILLING_READ","INVOICE_READ","REPORTING_FINANCIAL","PAYMENT_READ","VOUCHER_READ"],
  sales: ["POS_CREATE","POS_READ","POS_UPDATE","INVOICE_CREATE","CUSTOMER_READ","CUSTOMER_CREATE","PRODUCT_READ","QUOTE_CREATE","PAYMENT_CREATE"],
  warehouse: ["INVENTORY_READ","INVENTORY_CREATE","INVENTORY_UPDATE","PRODUCT_READ"],
  viewer: ["POS_READ","BILLING_READ","INVOICE_READ","CUSTOMER_READ","PRODUCT_READ","INVENTORY_READ","REPORTING_READ"],
};

export function permissionsForRole(role: string): PermissionKey[] {
  return ROLE_DEFINITIONS[role] ?? [];
}

export async function resolveUserPermissions(ctx: TrpcContext): Promise<string[]> {
  if (ctx.isSuperAdmin) return Object.values(PERMISSIONS) as string[];
  if (!ctx.user) return [];
  const userRole = (ctx.user.role as string) || "user";
  const rolePerms = new Set<string>(permissionsForRole(userRole));
  if (ctx.tenantId && ctx.user.customPermissions) {
    try {
      const custom = typeof ctx.user.customPermissions === "string" ? JSON.parse(ctx.user.customPermissions) : ctx.user.customPermissions;
      if (Array.isArray(custom)) custom.forEach((p: string) => rolePerms.add(p));
    } catch {}
  }
  return Array.from(rolePerms);
}

export async function checkPermission(ctx: TrpcContext, permission: PermissionKey): Promise<boolean> {
  const perms = await resolveUserPermissions(ctx);
  return perms.includes(permission);
}

export const PERMISSION_DENIED_MSG = "ليس لديك صلاحية لتنفيذ هذا الإجراء";

export function isOwnerOrAdmin(ctx: TrpcContext): boolean {
  if (ctx.isSuperAdmin) return true;
  if (!ctx.user) return false;
  return ctx.user.role === "admin" || ctx.user.role === "owner";
}

export function isAdmin(ctx: TrpcContext): boolean {
  if (ctx.isSuperAdmin) return true;
  if (!ctx.user) return false;
  return ctx.user.role === "admin";
}
