blank_issues_enabled: false
contact_links:
  - name: Discussion Forum
    url: https://github.com/dypos/dypos/discussions
    about: Ask questions and discuss with the community
  - name: Documentation
    url: https://dypos.smartportssoft.com/
    about: Read the dyposdocumentation before opening an issue
